import { SEOConfig } from '../core/types';
import { ShopifyProduct, ShopifyCollection, ShopifyStore } from './types';

/**
 * Generate Shopify Liquid template helpers for SEO
 */
export class ShopifyLiquidHelpers {
  /**
   * Generate Liquid template for product SEO meta tags
   */
  static generateProductMetaTemplate(): string {
    return `
{%- comment -%}
SEO Meta Tags for Product Pages
Generated by symmetrical-octo-guide
{%- endcomment -%}

{%- assign product_title = product.title | escape -%}
{%- assign product_description = product.description | strip_html | truncate: 160 | escape -%}
{%- assign product_image = product.featured_image | img_url: '1200x630' -%}
{%- assign product_url = shop.url | append: product.url -%}

<title>{{ product_title }}{% unless page_title contains shop.name %} - {{ shop.name }}{% endunless %}</title>
<meta name="description" content="{{ product_description }}">

{%- if product.tags.size > 0 -%}
<meta name="keywords" content="{{ product.tags | join: ', ' | escape }}">
{%- endif -%}

<!-- Open Graph -->
<meta property="og:type" content="product">
<meta property="og:title" content="{{ product_title }}">
<meta property="og:description" content="{{ product_description }}">
<meta property="og:url" content="{{ product_url }}">
<meta property="og:image" content="{{ product_image }}">
<meta property="og:site_name" content="{{ shop.name | escape }}">

<!-- Twitter Card -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{{ product_title }}">
<meta name="twitter:description" content="{{ product_description }}">
<meta name="twitter:image" content="{{ product_image }}">

<!-- Product-specific meta -->
<meta property="product:price:amount" content="{{ product.price | money_without_currency | remove: ',' }}">
<meta property="product:price:currency" content="{{ shop.currency }}">
<meta property="product:availability" content="{% if product.available %}in stock{% else %}out of stock{% endif %}">

{%- if product.compare_at_price > product.price -%}
<meta property="product:sale_price:amount" content="{{ product.price | money_without_currency | remove: ',' }}">
<meta property="product:original_price:amount" content="{{ product.compare_at_price | money_without_currency | remove: ',' }}">
{%- endif -%}
`.trim();
  }

  /**
   * Generate Liquid template for collection SEO meta tags
   */
  static generateCollectionMetaTemplate(): string {
    return `
{%- comment -%}
SEO Meta Tags for Collection Pages
Generated by symmetrical-octo-guide
{%- endcomment -%}

{%- assign collection_title = collection.title | escape -%}
{%- assign collection_description = collection.description | strip_html | truncate: 160 | escape -%}
{%- assign collection_image = collection.featured_image | img_url: '1200x630' -%}
{%- assign collection_url = shop.url | append: collection.url -%}

<title>{{ collection_title }}{% unless page_title contains shop.name %} - {{ shop.name }}{% endunless %}</title>
<meta name="description" content="{{ collection_description }}">

<!-- Open Graph -->
<meta property="og:type" content="website">
<meta property="og:title" content="{{ collection_title }}">
<meta property="og:description" content="{{ collection_description }}">
<meta property="og:url" content="{{ collection_url }}">
{%- if collection_image != blank -%}
<meta property="og:image" content="{{ collection_image }}">
{%- endif -%}
<meta property="og:site_name" content="{{ shop.name | escape }}">

<!-- Twitter Card -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{{ collection_title }}">
<meta name="twitter:description" content="{{ collection_description }}">
{%- if collection_image != blank -%}
<meta name="twitter:image" content="{{ collection_image }}">
{%- endif -%}
`.trim();
  }

  /**
   * Generate Liquid template for product structured data
   */
  static generateProductStructuredDataTemplate(): string {
    return `
{%- comment -%}
Product Structured Data (JSON-LD)
Generated by symmetrical-octo-guide
{%- endcomment -%}

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Product",
  "name": {{ product.title | json }},
  "description": {{ product.description | strip_html | json }},
  "image": [
    {%- for image in product.images -%}
      {{ image | img_url: '1200x1200' | json }}{% unless forloop.last %},{% endunless %}
    {%- endfor -%}
  ],
  "url": {{ shop.url | append: product.url | json }},
  "brand": {
    "@type": "Brand",
    "name": {{ product.vendor | json }}
  },
  "category": {{ product.type | json }},
  {%- if product.variants.first.sku != blank -%}
  "sku": {{ product.variants.first.sku | json }},
  {%- endif -%}
  {%- if product.variants.first.barcode != blank -%}
  "gtin": {{ product.variants.first.barcode | json }},
  {%- endif -%}
  "offers": {
    "@type": "Offer",
    "price": {{ product.price | money_without_currency | remove: ',' | json }},
    "priceCurrency": {{ shop.currency | json }},
    "availability": "https://schema.org/{% if product.available %}InStock{% else %}OutOfStock{% endif %}",
    "url": {{ shop.url | append: product.url | json }},
    "seller": {
      "@type": "Organization",
      "name": {{ shop.name | json }}
    }
    {%- if product.compare_at_price > product.price -%},
    "priceSpecification": {
      "@type": "UnitPriceSpecification",
      "price": {{ product.price | money_without_currency | remove: ',' | json }},
      "priceCurrency": {{ shop.currency | json }}
    }
    {%- endif -%}
  }
}
</script>
`.trim();
  }

  /**
   * Generate Liquid template for breadcrumb structured data
   */
  static generateBreadcrumbTemplate(): string {
    return `
{%- comment -%}
Breadcrumb Structured Data (JSON-LD)
Generated by symmetrical-octo-guide
{%- endcomment -%}

{%- unless template == 'index' -%}
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "name": "Home",
      "item": {{ shop.url | json }}
    }
    {%- if template contains 'collection' -%}
    ,{
      "@type": "ListItem",
      "position": 2,
      "name": "Collections",
      "item": {{ shop.url | append: '/collections' | json }}
    }
    ,{
      "@type": "ListItem",
      "position": 3,
      "name": {{ collection.title | json }},
      "item": {{ shop.url | append: collection.url | json }}
    }
    {%- elsif template contains 'product' -%}
    {%- if collection -%}
    ,{
      "@type": "ListItem",
      "position": 2,
      "name": {{ collection.title | json }},
      "item": {{ shop.url | append: collection.url | json }}
    }
    ,{
      "@type": "ListItem",
      "position": 3,
      "name": {{ product.title | json }},
      "item": {{ shop.url | append: product.url | json }}
    }
    {%- else -%}
    ,{
      "@type": "ListItem",
      "position": 2,
      "name": {{ product.title | json }},
      "item": {{ shop.url | append: product.url | json }}
    }
    {%- endif -%}
    {%- endif -%}
  ]
}
</script>
{%- endunless -%}
`.trim();
  }
}

/**
 * Generate SEO configuration for Shopify product
 */
export function generateProductSEOConfig(product: ShopifyProduct, store: ShopifyStore): SEOConfig {
  return {
    title: `${product.title} - ${store.name}`,
    description: product.description.substring(0, 160),
    keywords: product.tags,
    canonical: product.url,
    openGraph: {
      type: 'product',
      title: product.title,
      description: product.description.substring(0, 160),
      url: product.url,
      image: product.images[0],
      siteName: store.name,
    },
    twitter: {
      card: 'summary_large_image',
      title: product.title,
      description: product.description.substring(0, 160),
      image: product.images[0],
    },
  };
}

/**
 * Generate SEO configuration for Shopify collection
 */
export function generateCollectionSEOConfig(collection: ShopifyCollection, store: ShopifyStore): SEOConfig {
  return {
    title: `${collection.title} - ${store.name}`,
    description: collection.description.substring(0, 160),
    canonical: collection.url,
    openGraph: {
      type: 'website',
      title: collection.title,
      description: collection.description.substring(0, 160),
      url: collection.url,
      image: collection.image,
      siteName: store.name,
    },
    twitter: {
      card: 'summary_large_image',
      title: collection.title,
      description: collection.description.substring(0, 160),
      image: collection.image,
    },
  };
}